// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArTr9nBh-X8KsIMkYE60OyGxVMVpXhjsc',
    appId: '1:544945978990:web:6afb0e0384239fc6ce307f',
    messagingSenderId: '544945978990',
    projectId: 'fir-todo-b17',
    authDomain: 'fir-todo-b17.firebaseapp.com',
    storageBucket: 'fir-todo-b17.appspot.com',
    measurementId: 'G-F0SCE8J7EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1RH3EIdChylXlCnTnNSHSH1vWPBcWYxI',
    appId: '1:544945978990:android:6e6fefaf7225edc1ce307f',
    messagingSenderId: '544945978990',
    projectId: 'fir-todo-b17',
    storageBucket: 'fir-todo-b17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACh7tF-ZTUht-zF39McnUK1_uH4vh4V3U',
    appId: '1:544945978990:ios:cfa9c6f027485830ce307f',
    messagingSenderId: '544945978990',
    projectId: 'fir-todo-b17',
    storageBucket: 'fir-todo-b17.appspot.com',
    iosClientId: '544945978990-hptapv5uq6rccpubr8ll61c18cvqb8br.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.firebaseNoteTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACh7tF-ZTUht-zF39McnUK1_uH4vh4V3U',
    appId: '1:544945978990:ios:cfa9c6f027485830ce307f',
    messagingSenderId: '544945978990',
    projectId: 'fir-todo-b17',
    storageBucket: 'fir-todo-b17.appspot.com',
    iosClientId: '544945978990-hptapv5uq6rccpubr8ll61c18cvqb8br.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.firebaseNoteTwo',
  );
}
